spring:
  application:
    name: RedFish
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/redfish}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
