spring:
  application:
    name: RedFish
  datasource:
    url: jdbc:mysql://localhost:3307/redfish
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
